<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{b456ed00-d5bf-423c-93f9-9669130ca655}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbEventLoggerListener : FB_EventLoggerListenerImpl;
	aLoggedEvents : ARRAY[0..99] OF ST_LoggedEvent;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

fbEventLoggerListener(aLoggedEventsBuffer:= aLoggedEvents);]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>